spring.application.name=admin-crud
server.port=8090

# ===============================
# VIEW RESOLVER - JSP
# ===============================
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Static resources
spring.mvc.static-path-pattern=/static/**


# ===============================
# DATABASE - SQL SERVER
# ===============================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=admin_crud;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
